#!/usr/bin/with-contenv sh
exec openvpn --cd /config --config "/config/client.ovpn" --inactive "3600" --keepalive "10" "60" \
    --mssfix "1460" --route-delay "2" --route-up "/sbin/ip route del default" \
    --script-security "2" --mute-replay-warnings --auth-nocache
